BlackLagoon/Controllers/AmenityController.cs
using BlackLagoon.Application.Common.Interfaces;
using BlackLagoon.Domain.Entities;
using BlackLagoon.Infrastructure.Repository;
using BlackLagoon.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BlackLagoon.Web.Controllers
{
    public class AmenityController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IWebHostEnvironment webHostEnvironment;
        public AmenityController(IUnitOfWork _unitOfWork, IWebHostEnvironment _webHostEnvironment)
        {
            unitOfWork = _unitOfWork;
            webHostEnvironment = _webHostEnvironment;
        }
        public IActionResult Index()
        {
            var Amenities = unitOfWork.Amenity.GetAll(includeProperties:"Villa");
            return View(Amenities);
        }
        public IActionResult Create()
        {
            AmenityVM amenityVM = new()
            {
                VillaList = unitOfWork.Villa.GetAll().Select(Villa => new SelectListItem
                {
                    Text = Villa.Name,
                    Value = Villa.Id.ToString()
                })
            };
            return View(amenityVM);
        }
        [HttpPost]
        public IActionResult Create(AmenityVM obj)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Amenity.Add(obj.Amenity);
                unitOfWork.Save();
                TempData["success"] = "Amenity created successfully.";
                return RedirectToAction("Index");
            }
            else
            {
                obj.VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem { 
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                TempData["error"] = "Could not create Amenity.";
                return View(obj);
            }
        }
        public IActionResult Update(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Amenity = unitOfWork.Amenity.Get(u => u.Id == amenityId)
            };
            if (amenityVM.Amenity == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(amenityVM);
        }
        [HttpPost]
        public IActionResult Update(AmenityVM obj)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.Amenity.Update(obj.Amenity);
                unitOfWork.Save();
                TempData["success"] = "Amenity updated successfully.";
                return RedirectToAction("Index");
            }
            else
            {
                obj.VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                });
                TempData["error"] = "Could not update Amenity.";
                return View(obj);
            }
        }
        public IActionResult Delete(int amenityId)
        {
            AmenityVM amenityVM = new()
            {
                VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                Amenity = unitOfWork.Amenity.Get(u => u.Id == amenityId)
            };
            return View(amenityVM);
        }
        [HttpPost]
        public IActionResult Delete(AmenityVM obj)
        {
            Amenity? objFromDb = unitOfWork.Amenity.Get(u => u.Id == obj.Amenity.Id);
            if (objFromDb is not null)
            {
                unitOfWork.Amenity.Remove(objFromDb);
                unitOfWork.Save();
                TempData["success"] = "The amenity has been deleted successfully.";
                return RedirectToAction(nameof(Index));
            }
            TempData["error"] = "The amenity could not be deleted.";
            return View();
        }
    }
}

BlackLagoon/Controllers/VillaNumberController.cs
using BlackLagoon.Application.Common.Interfaces;
using BlackLagoon.Domain.Entities;
using BlackLagoon.Infrastructure.Data;
using BlackLagoon.Infrastructure.Repository;
using BlackLagoon.Web.Models.ViewModels;
using Microsoft.AspNetCore.Components.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BlackLagoon.Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        public VillaNumberController(IUnitOfWork _unitOfWork)
        {
            unitOfWork = _unitOfWork;
        }
        public IActionResult Index()
        {
            var villaNumbers = unitOfWork.VillaNumber.GetAll(includeProperties: "Villa");
            return View(villaNumbers);
        }
        public IActionResult Create() 
        {
            VillaNumberVM villaNumberVM = new()
            {
                VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                })
            };
            
            return View(villaNumberVM);
        }
        [HttpPost]
        public IActionResult Create(VillaNumberVM obj)
        {
            bool roomExists = unitOfWork.VillaNumber.Any(u => u.Villa_Number == obj.VillaNumber.Villa_Number);
            if (ModelState.IsValid && !roomExists)
            {
                unitOfWork.VillaNumber.Add(obj.VillaNumber);
                unitOfWork.Save();
                TempData["success"] = "Villa number added successfully.";
                return RedirectToAction(nameof(Index));
            }
            if (roomExists) TempData["error"] = "The villa Number already exists.";

            obj.VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            return View(obj);
        }
        public IActionResult Update(int villaNumberId)
        {
            VillaNumberVM villaNumberVM = new()
            {
                VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                VillaNumber = unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId)
            };
            if (villaNumberVM.VillaNumber == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villaNumberVM);
}
        [HttpPost]
        public IActionResult Update(VillaNumberVM obj)
        {
            if (ModelState.IsValid)
            {
                unitOfWork.VillaNumber.Update(obj.VillaNumber);
                unitOfWork.Save();
                TempData["success"] = "Villa number updated successfully.";
                return RedirectToAction(nameof(Index));
            }

            obj.VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem
            {
                Text = u.Name,
                Value = u.Id.ToString()
            });

            return View(obj);
        }
        public IActionResult Delete(int villaNumberId)
        {
            VillaNumberVM villaNumberVM = new()
            {
                VillaList = unitOfWork.Villa.GetAll().Select(u => new SelectListItem
                {
                    Text = u.Name,
                    Value = u.Id.ToString()
                }),
                VillaNumber = unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberId)
            };
            if (villaNumberVM.VillaNumber == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(villaNumberVM);
        }
        [HttpPost]
        public IActionResult Delete(VillaNumberVM villaNumberVM)
        {
            VillaNumber? objFromDb = unitOfWork.VillaNumber.Get(u => u.Villa_Number == villaNumberVM.VillaNumber.Villa_Number);
            if (objFromDb is not null)
            {
                unitOfWork.VillaNumber.Remove(objFromDb);
                unitOfWork.Save();
                TempData["success"] = "The villa number has been deleted successfully.";
                return RedirectToAction("Index");
            }
            TempData["error"] = "Villa number could not be deleted.";
            return View();
        }
    }
}

BlackLagoon/Views/Amenity/Create.cshtml
@model AmenityVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-gradient m-lg-0 py-3" style="background-color: #d66711">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> Create new villa number</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <div asp-validation-summary="ModelOnly"></div>
            <div class="p-3">
                @* <div asp-validation-summary="All"></div> *@
                <div class="form-floating py-1 col-12">
                    <select asp-for="@Model.Amenity.VillaId" asp-items="@Model.VillaList"
                            class="form-select border shadow">
                        <option disabled selected>--Select Villa--</option>
                    </select>
                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Name" class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Description" class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle-fill"></i>&nbsp; Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <button asp-controller="VillaNumber" asp-action="Index" class="btn btn-danger w-100" id="cancelButton">
                            <i class="bi bi-x-circle-fill"></i>&nbsp; Cancel
                        </button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial"></partial>
    }
    <script>
        document.getElementById("cancelButton").addEventListener("click", function (event) {
            event.preventDefault(); // Prevent form submission
            // Optionally, redirect to the desired URL using window.location.href
            window.location.href = "@Url.Action("Index", "VillaNumber")";
        });
    </script>
}

BlackLagoon/Views/Amenity/Delete.cshtml
@model AmenityVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Delete Villa Number</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input asp-for="Amenity.Id" hidden />
            <div class="p-3">

                <div class="form-floating py-1 col-12">
                    <select disabled asp-for="Amenity.VillaId" asp-items="@Model.VillaList"
                            class="form-select border shadow">
                        <option disabled selected>--Select Villa--</option>
                    </select>
                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Name" disabled class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Description" disabled class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class=" ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Delete
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Amenity" asp-action="Index" class="btn btn-danger w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

BlackLagoon/Views/Amenity/Index.cshtml
@model IEnumerable<Amenity>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-gradient m-lg-0 py-3" style="background-color: #d66711">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2"> Amenity list</h2>
            </div>
        </div>
    </div>
    <div class="card-body border-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Amenity" asp-action="Create" class="btn" style="background-color:#c43f3f">
                    <i class="bi bi-plus-circle"></i> Create New Amenity
                </a>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Villa Name</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model.OrderBy(amenity=>amenity.Villa.Name))
                {
                    <tr>
                        <td>@obj.Id</td>
                        <td>@obj.Name</td>
                        <td>@obj.Villa.Name</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Amenity" asp-action="Update" asp-route-amenityId="@obj.Id"
                                   class="btn btn-success mx-2 rounded-3">
                                    <i class="bi bi-pencil-fill"></i> Edit
                                </a>
                                <a asp-controller="Amenity" asp-action="Delete" asp-route-amenityId="@obj.Id"
                                   class="btn btn-danger mx-2 rounded-3">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

BlackLagoon/Views/Amenity/Update.cshtml
@model AmenityVM

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Update Amenity</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row">
            <input hidden asp-for="Amenity.Id" />
            <div class="p-3">
                @* <div asp-validation-summary="All"></div> *@
                <div class="form-floating py-1 col-12">
                    <select asp-for="Amenity.VillaId" asp-items="@Model.VillaList"
                            class="form-select border shadow">
                        <option disabled selected>--Select Villa--</option>
                    </select>
                    <label asp-for="Amenity.VillaId" class="ms-2"></label>
                    <span asp-validation-for="Amenity.VillaId" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Name" class="form-control border shadow" />
                    <label asp-for="Amenity.Name" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Amenity.Description" class="form-control border shadow" />
                    <label asp-for="Amenity.Description" class="ms-2"></label>
                    <span asp-validation-for="Amenity.Description" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Update
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Amenity" asp-action="Index" class="btn btn-danger w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}